# Take a sample of ARMD Dataset.

In [1]:
linked_features = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']

files_info = [
    {
        "name": "cultures_cohort",
        "path": "microbiology_cultures_cohort.csv",
        "merge_on": linked_features, 
        "dtype": {
            "ordering_mode": "object",
            "culture_description": "object",
            "was_positive": "Int64",
            "organism": "object",
            "antibiotic": "object",
            "susceptibility": "object"
        }
    },
    {
        "name": "ward_info",
        "path": "microbiology_cultures_ward_info.csv",
        "merge_on": linked_features, 
        "dtype": {
            "hosp_ward_IP": "Int64",
            "hosp_ward_OP": "Int64",
            "hosp_ward_ER": "Int64",
            "hosp_ward_ICU": "Int64"
        }
    },
    {
        "name": "prior_med",
        "path": "microbiology_cultures_prior_med.csv",
        "merge_on": linked_features,
        "dtype": {
            "medication_name": "object",
            "medication_time_to_culturetime": "Int64",
            "medication_category": "object"
        }
    },
    {
        "name": "microbial_resistance",
        "path": "microbiology_cultures_microbial_resistance.csv",
        "merge_on": linked_features, 
        "dtype": {
            "organism": "object",
            "antibiotic": "object",
            "resistant_time_to_culturetime": "Int64"
        }
    },
    {
        "name": "cultures_demographics",
        "path": "microbiology_cultures_demographics.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "age": "object",
            "gender": "object"
        }
    },
     {
        "name": "cultures_labs",
        "path": "microbiology_cultures_labs.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "Period_Day": "Int64",
            "Q75_wbc": "object",
            "Q25_wbc": "object",
            "median_wbc": "object",
            "Q25_neutrophils": "float32",
            "Q75_neutrophils": "float32",
            "median_neutrophils": "float32",
            "Q25_lymphocytes": "float32",
            "Q75_lymphocytes": "float32",
            "median_lymphocytes": "float32",
            "Q25_hgb": "object",
            "Q75_hgb": "object",
            "median_hgb": "object",
            "Q25_plt": "object",
            "Q75_plt": "object",
            "median_plt": "object",
            "Q75_na": "object",
            "Q25_na": "object",
            "median_na": "object",
            "Q75_hco3": "object",
            "Q25_hco3": "object",
            "median_hco3": "object",
            "Q75_bun": "object",
            "Q25_bun": "object",
            "median_bun": "object",
            "Q75_cr": "object",
            "Q25_cr": "object",
            "median_cr": "object",
            "Q75_lactate": "object",
            "Q25_lactate": "object",
            "median_lactate": "object",
            "Q75_procalcitonin": "object",
            "Q25_procalcitonin": "object",
            "median_procalcitonin": "object",
            "first_procalcitonin": "object",
            "last_procalcitonin": "object",
            "first_lactate":"object",
            "last_cr":"object",
            "first_cr":"object",
            "last_bun":"object",
            "first_bun":"object",
            "last_hco3":"object",
            "first_hco3":"object",
            "last_na":"object",
            "first_na":"object",
            "last_plt":"object",
            "first_plt":"object",
            "last_hgb":"object",
            "first_hgb":"object",
            "last_lymphocytes":"object",
            "first_lymphocytes":"object",
            "last_neutrophils":"object",
            "first_neutrophils":"object",
            "last_wbc":"object",
            "first_wbc":"object" 
        }
    },
    {
        "name": "cultures_vitals",
        "path": "microbiology_cultures_vitals.csv",
        "merge_on": linked_features[:3],
        "dtype": {
            "Q25_heartrate": "object",
            "Q75_heartrate": "object",
            "median_heartrate": "object",
            "Q25_resprate": "object",
            "Q75_resprate": "object",
            "median_resprate": "object",
            "Q25_temp": "object",
            "Q75_temp": "object",
            "median_temp": "object",
            "Q25_sysbp": "float32",
            "Q75_sysbp": "float32",
            "median_sysbp": "float32",
            "Q25_diasbp": "float32",
            "Q75_diasbp": "float32",
            "median_diasbp": "float32",
            "first_diasbp": "object",
            "last_diasbp": "object",
            "last_sysbp": "object",
            "first_sysbp": "object",
            "last_temp": "object",
            "first_temp": "object",
            "last_resprate": "object",
            "first_resprate": "object",
            "last_heartrate": "object",
            "first_heartrate": "object"
        }
    },
     {
        "name": "antibiotic_class_exposure",
        "path": "microbiology_cultures_antibiotic_class_exposure.csv",
        "merge_on": linked_features, 
        "dtype": {
            "medication_category": "object",
            "medication_name": "object",
            "antibiotic_class": "object",
            "time_to_culturetime": "Int64"
        }
    },
    {
        "name": "antibiotic_subtype_exposure",
        "path": "microbiology_cultures_antibiotic_subtype_exposure.csv",
        "merge_on": linked_features, 
        "dtype": {
            "medication_category": "object",
            "medication_name": "object",
            "antibiotic_subtype": "object",
            "antibiotic_subtype_category": "object",
            "medication_time_to_cultureTime": "Int64"
        }
    },
    {
        "name": "prior_infecting_organism",
        "path": "microbiology_culture_prior_infecting_organism.csv",
        "merge_on": linked_features, 
        "dtype": {
            "prior_organism": "object",
            "prior_infecting_organism_days_to_culutre": "Int64"
        }
    },
    {
        "name": "cultures_comorbidity",
        "path": "microbiology_cultures_comorbidity.csv",
        "merge_on": linked_features, 
        "dtype": {
            "comorbidity_component": "object",
            "comorbidity_component_start_days_culture": "Int64",
            "comorbidity_component_end_days_culture": "float32"
        }
    },
    {
        "name": "cultures_priorprocedures",
        "path": "microbiology_cultures_priorprocedures.csv",
        "merge_on": linked_features, 
        "dtype": {
            "procedure_description": "object",
            "procedure_time_to_culturetime": "Int64"
        }
    },
    {
        "name": "adi_scores",
        "path": "microbiology_cultures_adi_scores.csv",
        "merge_on": linked_features, 
        "dtype": {
            "adi_score": "object",
            "adi_state_rank": "object"
        }
    },
    {
        "name": "nursing_home_visits",
        "path": "microbiology_cultures_adi_scores.csv",
        "merge_on": linked_features, 
        "dtype": {
            "nursing_home_visit_culture": "Int64"
        }
    },
    {
        "name": "implied_susceptibility",
        "path": "microbiology_cultures_implied_susceptibility.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "organism": "object",
            "antibiotic": "object",
            "susceptibility": "object",
            "implied_susceptibility": "object"
        }
    }
    , {
        "name": "implied_susceptibility_rules",
        "path": "microbiology_cultures_implied_susceptibility.csv",
        "merge_on": None , 
        "dtype": {
            "Organism": "object",
            "Antibiotic": "object",
            "Susceptibility": "object",
        }
    }
]


# Enhanced Sampling 

In [5]:

import pandas as pd
import os


input_folder = 'doi_10_5061_dryad_jq2bvq8kp__v20250411/'
output_file = 'new_sample_one/'
linked_features = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']

os.makedirs(output_file, exist_ok=True)

df = pd.read_csv(input_folder + files_info[0]['path'], usecols=['anon_id', 'susceptibility'])

df = df[df['susceptibility'].isin(['Susceptible', 'Resistant'])]

sus_patients = df[df['susceptibility'] == 'Susceptible']['anon_id'].drop_duplicates().sample(n=500, random_state=42)
res_patients = df[df['susceptibility'] == 'Resistant']['anon_id'].drop_duplicates().sample(n=500, random_state=42)

pat_ids = pd.concat([sus_patients, res_patients]).reset_index(drop=True)

for file in files_info:
    size_bytes = os.path.getsize(input_folder + file['path'])
    size_gb = size_bytes / (1024 ** 3)  # Convert to GB
    if (size_gb < 2):
        df = pd.read_csv(input_folder + file['path'], dtype = file['dtype'] , na_values=['Null'], low_memory=False)
        df = df[df['anon_id'].isin(pat_ids)]
        df.to_parquet(output_file + file['name'] + '.parquet',  engine='pyarrow', index=False )
        print(f"Sample saved: {output_file + file['name'] + '.parquet'}")
    else:
        chunk_size = 1_000_000
        filtered_chunks = []
        for chunk in pd.read_csv(input_folder + file['path'], dtype=file['dtype'], na_values=['Null'], chunksize=chunk_size):
            filtered_chunk = chunk[chunk['anon_id'].isin(pat_ids)]
            filtered_chunks.append(filtered_chunk)
    
        if filtered_chunks:
            df = pd.concat(filtered_chunks, ignore_index=True)
            df.to_parquet(output_file + file['name'] + '.parquet', engine='pyarrow',  index=False)
            print(f"Sample Saved: {output_file + file['name']}.parquet")

print(f"\n Alhamdulillah the samples files done ✅")

Sample saved: new_sample_one/cultures_cohort.parquet
Sample saved: new_sample_one/ward_info.parquet
Sample saved: new_sample_one/prior_med.parquet
Sample saved: new_sample_one/microbial_resistance.parquet
Sample saved: new_sample_one/cultures_demographics.parquet
Sample saved: new_sample_one/cultures_labs.parquet
Sample saved: new_sample_one/cultures_vitals.parquet
Sample saved: new_sample_one/antibiotic_class_exposure.parquet
Sample saved: new_sample_one/antibiotic_subtype_exposure.parquet
Sample saved: new_sample_one/prior_infecting_organism.parquet
Sample Saved: new_sample_one/cultures_comorbidity.parquet
Sample saved: new_sample_one/cultures_priorprocedures.parquet
Sample saved: new_sample_one/adi_scores.parquet
Sample saved: new_sample_one/nursing_home_visits.parquet
Sample saved: new_sample_one/implied_susceptibility.parquet
Sample saved: new_sample_one/implied_susceptibility_rules.parquet

 Alhamdulillah the samples files done ✅


## Check the data samples files

In [7]:
import pandas as pd

output_file = 'new_sample_one/'
for file in files_info:
    df = pd.read_parquet(output_file + file['name'] + '.parquet', engine='pyarrow')
    print(f"file {output_file + file['name'] + '.parquet'}:  ")
    print(df.head())
    print('-----------------------------------------------')

file new_sample_one/cultures_cohort.parquet:  
     anon_id  pat_enc_csn_id_coded  order_proc_id_coded  \
0   JC854129          131362032609            903673882   
1   JC987382          131018782688            401046280   
2   JC525636              16380445            329638112   
3  JC1873593          131236477728            531304610   
4   JC517943          131239407403            538396799   

     order_time_jittered_utc ordering_mode culture_description  was_positive  \
0  2023-09-24 03:45:00+00:00    Outpatient               URINE             1   
1  2012-05-12 16:08:00+00:00     Inpatient               URINE             1   
2  2008-09-04 01:27:00+00:00    Outpatient               URINE             1   
3  2017-07-09 21:06:00+00:00    Outpatient               URINE             1   
4  2017-09-08 03:34:00+00:00    Outpatient               URINE             1   

                organism      antibiotic susceptibility  
0  KLEBSIELLA PNEUMONIAE     Ceftazidime    Susceptible  
1

# Samples file prapation befor the merge:

## cultures_cohort.parquet file preparing

In [1]:
import pandas as pd

sample_folder = 'new_sample_one/'
df = pd.read_parquet(sample_folder + "cultures_cohort.parquet")
print(f'Shape: {df.shape}')
print(f"# of patients: {df['anon_id'].unique().size}")

Shape: (29632, 10)
# of patients: 997


not as i expected; but i will keep it for now 

In [4]:
df['susceptibility'].unique()

array(['Susceptible', 'Intermediate', 'Resistant', None, 'Synergism',
       'Inconclusive'], dtype=object)

In [6]:
df = df[df['susceptibility'].isin(['Susceptible', 'Resistant'])]

In [8]:
print(f"# of patients: {df['anon_id'].unique().size}")
print(f"My target susceptibility: {df['susceptibility'].unique()}")

# of patients: 997
My target susceptibility: ['Susceptible' 'Resistant']


In [10]:
print(df['susceptibility'].value_counts())


susceptibility
Susceptible    20826
Resistant       5029
Name: count, dtype: int64


My explanation for class distribution:
I start with 500 Susceptible + 500 Resistant;
And by using patent id; i take all the recored for this patien; in the beganing the patent is Susceptible for specific antibiotic but after he faced this antibiotic many times he had a  Resistant.

so if i faced any problems with imbalance class i would deal with it inshaa allah.

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='susceptibility', data=df, order=['Susceptible', 'Resistant'])
plt.title("Distribution of Susceptibility Categories")
plt.ylabel("Count")
plt.show()


In [14]:
df['susceptibility'] = df['susceptibility'].map({
    'Susceptible': 0,
    'Resistant': 1,
})

In [15]:
print(df['susceptibility'].value_counts())


susceptibility
0    20826
1     5029
Name: count, dtype: int64


In [16]:
df['susceptibility'] = df['susceptibility'].astype('Int8')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25855 entries, 0 to 29626
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  25855 non-null  object
 1   pat_enc_csn_id_coded     25855 non-null  int64 
 2   order_proc_id_coded      25855 non-null  int64 
 3   order_time_jittered_utc  25855 non-null  object
 4   ordering_mode            25140 non-null  object
 5   culture_description      25855 non-null  object
 6   was_positive             25855 non-null  Int64 
 7   organism                 25855 non-null  object
 8   antibiotic               25855 non-null  object
 9   susceptibility           25855 non-null  Int8  
dtypes: Int64(1), Int8(1), int64(2), object(6)
memory usage: 2.0+ MB


In [23]:
df['was_positive'].value_counts()

was_positive
1    25855
Name: count, dtype: Int64

I will Drop `was_positive` because:
Every row is positive (was_positive == 1 for 100% of samples). So: It provides zero predictive power.

So my final cleaned file should drop:
- `ordering_mode` (procedural, not useful)
- `culture_description` (likely redundant)
- `was_positive` (constant, uninformative)



In [26]:
df = df.drop(columns=['ordering_mode', 'culture_description', 'was_positive'])


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25855 entries, 0 to 29626
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  25855 non-null  object
 1   pat_enc_csn_id_coded     25855 non-null  int64 
 2   order_proc_id_coded      25855 non-null  int64 
 3   order_time_jittered_utc  25855 non-null  object
 4   organism                 25855 non-null  object
 5   antibiotic               25855 non-null  object
 6   susceptibility           25855 non-null  Int8  
dtypes: Int8(1), int64(2), object(4)
memory usage: 1.4+ MB


In [30]:
df['organism'].value_counts()

organism
ESCHERICHIA COLI                        14134
KLEBSIELLA PNEUMONIAE                    2193
STAPHYLOCOCCUS AUREUS                    1573
PROTEUS MIRABILIS                        1412
ENTEROCOCCUS SPECIES                      983
                                        ...  
CORYNEBACTERIUM PSEUDODIPHTHERITICUM        4
NOCARDIA TRANSVALENSIS                      4
CLOSTRIDIUM PERFRINGENS                     4
BACTEROIDES SPECIES                         3
BETA STREPTOCOCCUS GROUP C                  3
Name: count, Length: 87, dtype: int64

87 unique organisms!!
Too many rare organisms (e.g., ≤10 cases) can:
- Add noise
- Cause overfitting
- Make encoding sparse and inefficient

Group Rare Organisms
Group all organisms with fewer than, say, 100 cases into `other`:

In [34]:
organism_counts = df['organism'].value_counts()
common_organisms = organism_counts[organism_counts >= 100].index

df['organism'] = df['organism'].apply(lambda x: x if x in common_organisms else 'other')


In [36]:
df['organism'].value_counts()

organism
ESCHERICHIA COLI                      14134
KLEBSIELLA PNEUMONIAE                  2193
STAPHYLOCOCCUS AUREUS                  1573
PROTEUS MIRABILIS                      1412
other                                  1268
ENTEROCOCCUS SPECIES                    983
PSEUDOMONAS AERUGINOSA                  867
ENTEROBACTER CLOACAE COMPLEX            480
MUCOID PSEUDOMONAS AERUGINOSA           436
COAG NEGATIVE STAPHYLOCOCCUS            368
STAPH AUREUS {MRSA}                     296
ACHROMOBACTER XYLOSOXIDANS              295
KLEBSIELLA OXYTOCA                      235
STREPTOCOCCUS AGALACTIAE (GROUP B)      219
CITROBACTER KOSERI                      211
CITROBACTER FREUNDII COMPLEX            193
SERRATIA MARCESCENS                     191
PROVIDENCIA RETTGERI                    189
MORGANELLA MORGANII                     163
ENTEROCOCCUS FAECALIS                   149
Name: count, dtype: int64

**Convert Categorical to Numeric for Modeling**

In [39]:
df['organism'] = df['organism'].astype('category')
df['organism'] = df['organism'].cat.codes


In [41]:
df['organism'].value_counts()

organism
7     14134
9      2193
17     1573
12     1412
19     1268
6       983
14      867
4       480
11      436
3       368
16      296
0       295
8       235
18      219
2       211
1       193
15      191
13      189
10      163
5       149
Name: count, dtype: int64

In [43]:
df['antibiotic'].value_counts()

antibiotic
Ciprofloxacin                    1800
Trimethoprim/Sulfamethoxazole    1772
Gentamicin                       1768
Levofloxacin                     1723
Ampicillin                       1535
Piperacillin/Tazobactam          1393
Nitrofurantoin                   1378
Cefazolin                        1360
Ceftriaxone                      1177
Meropenem                        1146
Tetracycline                     1142
Ceftazidime                      1138
Amikacin                         1102
Ertapenem                         926
Tobramycin                        859
Amoxicillin/Clavulanic Acid       834
Cefoxitin                         745
Cefepime                          606
Vancomycin                        410
Penicillin                        405
Aztreonam                         365
Clindamycin                       321
Erythromycin                      318
Ampicillin/Sulbactam              310
Linezolid                         262
Oxacillin                         233
M

**Strategy (Same as Organism)**

Group rare antibiotics (less than 100 counts)

In [46]:

antibiotic_counts = df['antibiotic'].value_counts()
common_antibiotics = antibiotic_counts[antibiotic_counts >= 100].index

df['antibiotic'] = df['antibiotic'].apply(lambda x: x if x in common_antibiotics else 'other')


**Convert to Category + Code**

In [49]:
df['antibiotic'] = df['antibiotic'].astype('category')
df['antibiotic'] = df['antibiotic'].cat.codes


In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25855 entries, 0 to 29626
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  25855 non-null  object
 1   pat_enc_csn_id_coded     25855 non-null  int64 
 2   order_proc_id_coded      25855 non-null  int64 
 3   order_time_jittered_utc  25855 non-null  object
 4   organism                 25855 non-null  int8  
 5   antibiotic               25855 non-null  int8  
 6   susceptibility           25855 non-null  Int8  
dtypes: Int8(1), int64(2), int8(2), object(2)
memory usage: 1.1+ MB


In [53]:
import os
os.makedirs('new_sample_one_processed', exist_ok=True)
df.to_parquet("new_sample_one_processed/processed_cultures_cohort.parquet", index=False)
print(f"The processed_cultures_cohort.parquet is saved :)")

The processed_cultures_cohort.parquet is saved :)


### check cultures_cohort.parquet

In [56]:
import pandas as pd

df = pd.read_parquet("new_sample_one_processed/processed_cultures_cohort.parquet")
print(f'Shape: {df.shape}')
print(f"# of patients: {df['anon_id'].unique().size}")
print(df['susceptibility'].value_counts())

Shape: (25855, 7)
# of patients: 997
susceptibility
0    20826
1     5029
Name: count, dtype: Int64


In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25855 entries, 0 to 25854
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  25855 non-null  object
 1   pat_enc_csn_id_coded     25855 non-null  int64 
 2   order_proc_id_coded      25855 non-null  int64 
 3   order_time_jittered_utc  25855 non-null  object
 4   organism                 25855 non-null  int8  
 5   antibiotic               25855 non-null  int8  
 6   susceptibility           25855 non-null  Int8  
dtypes: Int8(1), int64(2), int8(2), object(2)
memory usage: 909.1+ KB


## cultures_vitals.parquet file preparing

Processing for `cultures_vitals.parquet`:
My `cultures_vitals.parquet` not have a timestamp column at all:
That means this file (`cultures_vitals.parquet`) already contains aggregated features (e.g., `median`/`first`/`last` only) — not raw time-stamped vitals. So In this case i will:
- Keep cols: `median`, `first`, and `last` values for each vital sign.
- Compute the Delta features: the change between `first` and `last` (e.g., `delta_heartrate`), capturing the trend over time.

The resulting dataset will contain one row per patient with informative, time-aware features that can help predict antibiotic resistance.

In [41]:
sample_folder = 'new_sample_one/'

vitals = pd.read_parquet(sample_folder + "cultures_vitals.parquet")

print(vitals.columns)
print(vitals.shape)

Index(['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded',
       'Q25_heartrate', 'Q75_heartrate', 'median_heartrate', 'Q25_resprate',
       'Q75_resprate', 'median_resprate', 'Q25_temp', 'Q75_temp',
       'median_temp', 'Q25_sysbp', 'Q75_sysbp', 'median_sysbp', 'Q25_diasbp',
       'Q75_diasbp', 'median_diasbp', 'first_diasbp', 'last_diasbp',
       'last_sysbp', 'first_sysbp', 'last_temp', 'first_temp', 'last_resprate',
       'first_resprate', 'last_heartrate', 'first_heartrate'],
      dtype='object')
(21809, 28)


In [43]:
import pandas as pd

vitals_cols = [
    'anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded',
    'median_heartrate', 'first_heartrate', 'last_heartrate',
    'median_resprate', 'first_resprate', 'last_resprate',
    'median_temp', 'first_temp', 'last_temp',
    'median_sysbp', 'first_sysbp', 'last_sysbp',
    'median_diasbp', 'first_diasbp', 'last_diasbp'
]

vitals[vitals_cols[3:]] = vitals[vitals_cols[3:]].apply(pd.to_numeric, errors='coerce')

vitals = vitals[vitals_cols]

vital_signs = ['heartrate', 'resprate', 'temp', 'sysbp', 'diasbp']

for v in vital_signs:
    first_col = f'first_{v}'
    last_col = f'last_{v}'
    delta_col = f'delta_{v}'
    vitals[delta_col] = vitals[last_col] - vitals[first_col]


In [45]:
vitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21809 entries, 0 to 21808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               21809 non-null  object 
 1   pat_enc_csn_id_coded  21809 non-null  int64  
 2   order_proc_id_coded   21809 non-null  int64  
 3   median_heartrate      21777 non-null  float64
 4   first_heartrate       7224 non-null   float64
 5   last_heartrate        8467 non-null   float64
 6   median_resprate       21013 non-null  float64
 7   first_resprate        5678 non-null   float64
 8   last_resprate         4452 non-null   float64
 9   median_temp           21457 non-null  float64
 10  first_temp            4456 non-null   float64
 11  last_temp             2715 non-null   float64
 12  median_sysbp          21428 non-null  float32
 13  first_sysbp           4451 non-null   float64
 14  last_sysbp            6175 non-null   float64
 15  median_diasbp      

My vitals data is sparse — for many patients, the first and/or last readings weren't available in the 7-day window.

Using delta features alone may drastically reduce my sample size during modeling or training.

So i will keep rows where i have at least one usable delta - and avoid dropping too much data.

In [48]:
vital_signs = ['heartrate', 'resprate', 'temp', 'sysbp', 'diasbp']

conditions = [
    vitals[f'first_{v}'].notna() & vitals[f'last_{v}'].notna()
    for v in vital_signs
]

condition = conditions[0]
for cond in conditions[1:]:
    condition |= cond

vitals = vitals[condition].copy()

drop_cols = [f'first_{v}' for v in vital_signs] + [f'last_{v}' for v in vital_signs]
vitals.drop(columns=drop_cols, inplace=True)

print(vitals.shape)


(5282, 13)


In [50]:
vitals.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5282 entries, 2 to 21807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               5282 non-null   object 
 1   pat_enc_csn_id_coded  5282 non-null   int64  
 2   order_proc_id_coded   5282 non-null   int64  
 3   median_heartrate      5267 non-null   float64
 4   median_resprate       5219 non-null   float64
 5   median_temp           5240 non-null   float64
 6   median_sysbp          5120 non-null   float32
 7   median_diasbp         5120 non-null   float32
 8   delta_heartrate       2680 non-null   float64
 9   delta_resprate        1124 non-null   float64
 10  delta_temp            429 non-null    float64
 11  delta_sysbp           1049 non-null   float64
 12  delta_diasbp          1047 non-null   float64
dtypes: float32(2), float64(8), int64(2), object(1)
memory usage: 536.5+ KB


In [52]:
vitals.to_parquet("new_sample_one_processed/processed_cultures_vitals.parquet", index=False)
print(f"The processed_cultures_vitals.parquet is saved :)")

The processed_cultures_vitals.parquet is saved :)


In [54]:
vitals.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5282 entries, 2 to 21807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               5282 non-null   object 
 1   pat_enc_csn_id_coded  5282 non-null   int64  
 2   order_proc_id_coded   5282 non-null   int64  
 3   median_heartrate      5267 non-null   float64
 4   median_resprate       5219 non-null   float64
 5   median_temp           5240 non-null   float64
 6   median_sysbp          5120 non-null   float32
 7   median_diasbp         5120 non-null   float32
 8   delta_heartrate       2680 non-null   float64
 9   delta_resprate        1124 non-null   float64
 10  delta_temp            429 non-null    float64
 11  delta_sysbp           1049 non-null   float64
 12  delta_diasbp          1047 non-null   float64
dtypes: float32(2), float64(8), int64(2), object(1)
memory usage: 536.5+ KB


## check cultures_vitals.parquet file

In [57]:

vitals = pd.read_parquet("new_sample_one_processed/processed_cultures_vitals.parquet")
vitals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5282 entries, 0 to 5281
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               5282 non-null   object 
 1   pat_enc_csn_id_coded  5282 non-null   int64  
 2   order_proc_id_coded   5282 non-null   int64  
 3   median_heartrate      5267 non-null   float64
 4   median_resprate       5219 non-null   float64
 5   median_temp           5240 non-null   float64
 6   median_sysbp          5120 non-null   float32
 7   median_diasbp         5120 non-null   float32
 8   delta_heartrate       2680 non-null   float64
 9   delta_resprate        1124 non-null   float64
 10  delta_temp            429 non-null    float64
 11  delta_sysbp           1049 non-null   float64
 12  delta_diasbp          1047 non-null   float64
dtypes: float32(2), float64(8), int64(2), object(1)
memory usage: 495.3+ KB


## cultures_labs.parquet file preparing

In [101]:
import pandas as pd

sample_folder = 'new_sample_one/'
labs = pd.read_parquet(sample_folder + "cultures_labs.parquet")


In [103]:
print(f"Shape: {labs.shape}")
print("Columns:\n", labs.columns)

Shape: (8655, 59)
Columns:
 Index(['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'Period_Day',
       'Q75_wbc', 'Q25_wbc', 'median_wbc', 'Q25_neutrophils',
       'Q75_neutrophils', 'median_neutrophils', 'Q25_lymphocytes',
       'Q75_lymphocytes', 'median_lymphocytes', 'Q25_hgb', 'Q75_hgb',
       'median_hgb', 'Q25_plt', 'Q75_plt', 'median_plt', 'Q75_na', 'Q25_na',
       'median_na', 'Q75_hco3', 'Q25_hco3', 'median_hco3', 'Q75_bun',
       'Q25_bun', 'median_bun', 'Q75_cr', 'Q25_cr', 'median_cr', 'Q75_lactate',
       'Q25_lactate', 'median_lactate', 'Q75_procalcitonin',
       'Q25_procalcitonin', 'median_procalcitonin', 'first_procalcitonin',
       'last_procalcitonin', 'last_lactate', 'first_lactate', 'last_cr',
       'first_cr', 'last_bun', 'first_bun', 'last_hco3', 'first_hco3',
       'last_na', 'first_na', 'last_plt', 'first_plt', 'last_hgb', 'first_hgb',
       'last_lymphocytes', 'first_lymphocytes', 'last_neutrophils',
       'first_neutrophils', 'last_wbc',

In [105]:
labs.head()

anon_id  pat_enc_csn_id_coded  order_proc_id_coded  Period_Day Q75_wbc  \
0  JC1044165          131368594903            928221503          14    None   
1  JC2049852          131367083789            922422294          14    None   
2   JC679507          131007220411            358532443          14    None   
3  JC1072936          131243315393            546789757          14    None   
4   JC973259          131013249372            382333782          14    None   

  Q25_wbc median_wbc  Q25_neutrophils  Q75_neutrophils  median_neutrophils  \
0    None       None              NaN              NaN                 NaN   
1    None       None              NaN              NaN                 NaN   
2    None       None              NaN              NaN                 NaN   
3    None       None              NaN              NaN                 NaN   
4    None       None              NaN              NaN                 NaN   

   ...  last_plt  first_plt  last_hgb first_hgb last_lymphocytes  \
0  ...      None       None      None      None             None   
1  ...      None       None      None      None             None   
2  ...      None       None      None      None             None   
3  ...      None       None      None      None             None   
4  ...      None       None      None      None             None   

  first_lymphocytes last_neutrophils first_neutrophils last_wbc first_wbc  
0              None             None              None     None      None  
1              None             None              None     None      None  
2              None             None              None     None      None  
3              None             None              None     None      None  
4              None             None              None     None      None  

[5 rows x 59 columns]

In [107]:
labs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8655 entries, 0 to 8654
Data columns (total 59 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               8655 non-null   object 
 1   pat_enc_csn_id_coded  8655 non-null   int64  
 2   order_proc_id_coded   8655 non-null   int64  
 3   Period_Day            8655 non-null   Int64  
 4   Q75_wbc               8481 non-null   object 
 5   Q25_wbc               8481 non-null   object 
 6   median_wbc            8481 non-null   object 
 7   Q25_neutrophils       2367 non-null   float32
 8   Q75_neutrophils       2367 non-null   float32
 9   median_neutrophils    2367 non-null   float32
 10  Q25_lymphocytes       2385 non-null   float32
 11  Q75_lymphocytes       2385 non-null   float32
 12  median_lymphocytes    2385 non-null   float32
 13  Q25_hgb               8489 non-null   object 
 14  Q75_hgb               8489 non-null   object 
 15  median_hgb           


I will select a meaningful subset of labs:

- `Median` values (central tendency)
- Delta (`last` - `first`) when both are present

Convert object columns to numeric
Calculate delta values like we did for vitals
Drop first_ and last_, keep only delta_ and median_

- I will drop those cols because data `first_*` and `last_*` values are often sparse (e.g., `first_procalcitonin` has only 12 values) + reducing redundancy and dimensionalities + preventing data leakage.

In [110]:
import pandas as pd

sample_folder = 'new_sample_one/'
labs = pd.read_parquet(sample_folder + "cultures_labs.parquet")

labs_cols_base = [
    'anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded'
]

labs_vars = ['wbc', 'neutrophils', 'lymphocytes', 'hgb', 'plt', 'na', 'hco3', 'bun', 'cr', 'lactate', 'procalcitonin']

median_cols = [f'median_{var}' for var in labs_vars]
first_cols = [f'first_{var}' for var in labs_vars]
last_cols = [f'last_{var}' for var in labs_vars]

labs = labs[labs_cols_base + median_cols + first_cols + last_cols]

for col in median_cols + first_cols + last_cols:
    labs[col] = pd.to_numeric(labs[col], errors='coerce')

for var in labs_vars:
    first = labs[f'first_{var}']
    last = labs[f'last_{var}']
    labs[f'delta_{var}'] = last - first
    labs.loc[first.isna() | last.isna(), f'delta_{var}'] = pd.NA

labs_final = labs[labs_cols_base + median_cols + [f'delta_{var}' for var in labs_vars]]
labs_final = labs_final.dropna(subset=median_cols + [f'delta_{var}' for var in labs_vars], how='all')

print(labs_final.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8655 entries, 0 to 8654
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               8655 non-null   object 
 1   pat_enc_csn_id_coded  8655 non-null   int64  
 2   order_proc_id_coded   8655 non-null   int64  
 3   median_wbc            8481 non-null   float64
 4   median_neutrophils    2367 non-null   float32
 5   median_lymphocytes    2385 non-null   float32
 6   median_hgb            8489 non-null   float64
 7   median_plt            8475 non-null   float64
 8   median_na             8395 non-null   float64
 9   median_hco3           8438 non-null   float64
 10  median_bun            8418 non-null   float64
 11  median_cr             8485 non-null   float64
 12  median_lactate        3452 non-null   float64
 13  median_procalcitonin  782 non-null    float64
 14  delta_wbc             647 non-null    float64
 15  delta_neutrophils    

OMG extremely sparse - Yarab maysabib mashakel ba3den:)
- 13 `median_*` features — good overall coverage
- 12 `delta_*` features — most are extremely sparse or entirely missing (TT_TT).

| Feature                             | Non-null Count | Notes                          |
|-------------------------------------|----------------|--------------------------------|
| `delta_wbc`                         | 647            | Usable, but <10% of rows       |
| `delta_na`, `delta_cr`, `delta_bun`| 100–140        | Marginally usable              |
| `delta_lactate`                     | 7              | Nearly unusable                |
| `delta_procalcitonin`, `delta_hgb`, etc. | 0              | Unusable (no data available)   |


### What This Implies

- **`median_*` features are solid** — they cover most rows and summarize central trends well.

- **Most `delta_*` features are too sparse to be useful**:
  - Using them in modeling may either introduce noise or cause instability 😭.
  - Features with **0 non-null values** should be **dropped**.
  - For **low-count features** (e.g., <1–5% non-null), it may be better to drop them:
    - But i will use **models robust to missingness** (e.g., XGBoost with `missing` parameter).
    - So i will drop columns with 0 non-null values or <1% non-null


In [115]:
threshold = 0.01  # 1%

labs_filtered = labs_final.dropna(axis=1, thresh=int(len(labs) * threshold))

print(f"Original shape: {labs_final.shape}")
print(f"Filtered shape: {labs_filtered.shape}")


Original shape: (8655, 25)
Filtered shape: (8655, 19)


In [117]:
labs_filtered.to_parquet("new_sample_one_processed/processed_cultures_labs.parquet", index=False)
print(f"The processed_cultures_labs.parquet is saved :)")

## check processed_cultures_labs.parquet

In [120]:
import pandas as pd
labs = pd.read_parquet("new_sample_one_processed/processed_cultures_labs.parquet")
labs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8655 entries, 0 to 8654
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   anon_id               8655 non-null   object 
 1   pat_enc_csn_id_coded  8655 non-null   int64  
 2   order_proc_id_coded   8655 non-null   int64  
 3   median_wbc            8481 non-null   float64
 4   median_neutrophils    2367 non-null   float32
 5   median_lymphocytes    2385 non-null   float32
 6   median_hgb            8489 non-null   float64
 7   median_plt            8475 non-null   float64
 8   median_na             8395 non-null   float64
 9   median_hco3           8438 non-null   float64
 10  median_bun            8418 non-null   float64
 11  median_cr             8485 non-null   float64
 12  median_lactate        3452 non-null   float64
 13  median_procalcitonin  782 non-null    float64
 14  delta_wbc             647 non-null    float64
 15  delta_na             

## cultures_meds.parquet file preparing

In [1]:
import pandas as pd

sample_folder = 'new_sample_one/'
meds = pd.read_parquet(sample_folder + "prior_med.parquet")
meds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10597 entries, 0 to 10596
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   anon_id                         10597 non-null  object
 1   pat_enc_csn_id_coded            10597 non-null  int64 
 2   order_proc_id_coded             10597 non-null  int64 
 3   order_time_jittered_utc         10597 non-null  object
 4   medication_name                 10597 non-null  object
 5   medication_time_to_culturetime  10597 non-null  Int64 
 6   medication_category             10597 non-null  object
dtypes: Int64(1), int64(2), object(4)
memory usage: 590.0+ KB


In [3]:
meds['medication_name'].value_counts()

medication_name
Cefazolin        4621
Metronidazole    1120
Ciprofloxacin     977
Levofloxacin      951
Vancomycin        593
Ertapenem         430
Colistin          405
Ceftriaxone       386
Aztreonam         368
Gentamicin        368
Cefepime          102
Ampicillin         76
Ceftazidime        71
Linezolid          68
Amikacin           61
Name: count, dtype: int64

In [5]:
meds['medication_category'].value_counts()

medication_category
CEF      4621
MET1     1120
CIP3      977
LEV       951
VAN       593
ERT       430
COL       405
CEF2      386
AZT1      368
GEN1      368
CEF6      102
AMP1       76
CEF11      71
LIN        68
AMI        61
Name: count, dtype: int64

There’s a 1:1 mapping between `medication_name` and `medication_category` - so i  will pick one `medication_category`.

**Convert to Category + Codes**

In [9]:
meds['medication_category'] = meds['medication_category'].astype('category')
meds['medication_category'] = meds['medication_category'].cat.codes


In [11]:
meds['medication_category'].value_counts()

medication_category
3     4621
13    1120
7      977
11     951
14     593
9      430
8      405
5      386
2      368
10     368
6      102
1       76
4       71
12      68
0       61
Name: count, dtype: int64

In [13]:
meds['medication_time_to_culturetime'].value_counts()

medication_time_to_culturetime
2       32
41      31
35      29
17      29
21      25
        ..
1251     1
1702     1
2110     1
179      1
1445     1
Name: count, Length: 2817, dtype: Int64

In [15]:
meds['medication_time_to_culturetime'].max()

5586

In [17]:
meds['medication_time_to_culturetime'].min()

1

`medication_time_to_culturetime` has a wide range — from 1 to 5586 days before culture - a range from 1 to 5586 days (~15.3 years):
- Values within a reasonable clinical window, like 0–90 days, are potentially useful.
- These could reflect recent treatments that impact microbiological resistance.
- Very large values (years ago) are likely not relevant to the current infection episode.
- 5586 days is almost certainly old history — e.g., prior admissions, legacy data.
- Including them might introduce noise.

**Bacteria evolve quickly:**
- Resistance can develop or disappear in weeks or months.
- An antibiotic used 5+ years ago probably doesn't affect the bacteria causing an infection today.

I will create binary flag for "any med within 30 days"

In [20]:
import pandas as pd


meds = meds.drop(columns=['medication_name'])

meds = meds[meds['medication_time_to_culturetime'] <= 180]

meds['med_within_30_days'] = meds['medication_time_to_culturetime'] <= 30


In [22]:
meds.shape

(2085, 7)

In [24]:
meds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2085 entries, 0 to 10596
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   anon_id                         2085 non-null   object 
 1   pat_enc_csn_id_coded            2085 non-null   int64  
 2   order_proc_id_coded             2085 non-null   int64  
 3   order_time_jittered_utc         2085 non-null   object 
 4   medication_time_to_culturetime  2085 non-null   Int64  
 5   medication_category             2085 non-null   int8   
 6   med_within_30_days              2085 non-null   boolean
dtypes: Int64(1), boolean(1), int64(2), int8(1), object(2)
memory usage: 105.9+ KB


In [26]:
meds.to_parquet("new_sample_one_processed/processed_prior_med.parquet", index=False)
print(f"The processed_prior_med.parquet is saved :)")

The processed_prior_med.parquet is saved :)


## check /processed_prior_med.parquet file

In [28]:
import pandas as pd

meds = pd.read_parquet("new_sample_one_processed/processed_prior_med.parquet")
meds.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2085 entries, 0 to 2084
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   anon_id                         2085 non-null   object 
 1   pat_enc_csn_id_coded            2085 non-null   int64  
 2   order_proc_id_coded             2085 non-null   int64  
 3   order_time_jittered_utc         2085 non-null   object 
 4   medication_time_to_culturetime  2085 non-null   Int64  
 5   medication_category             2085 non-null   int8   
 6   med_within_30_days              2085 non-null   boolean
dtypes: Int64(1), boolean(1), int64(2), int8(1), object(2)
memory usage: 89.7+ KB


## cultures_demographics.parquet file praparing

In [79]:
import pandas as pd

demo = pd.read_parquet("new_sample_one/cultures_demographics.parquet")
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4875 entries, 0 to 4874
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   anon_id               4875 non-null   object
 1   pat_enc_csn_id_coded  4875 non-null   int64 
 2   order_proc_id_coded   4875 non-null   int64 
 3   age                   4875 non-null   object
 4   gender                4875 non-null   object
dtypes: int64(2), object(3)
memory usage: 190.6+ KB


In [81]:
demo['gender'].value_counts()

gender
0    3285
1    1590
Name: count, dtype: int64

In [83]:
demo['age'].value_counts()

age
65-74 years    928
75-84 years    855
55-64 years    681
25-34 years    662
45-54 years    521
35-44 years    411
18-24 years    282
85-89 years    279
above 90       256
Name: count, dtype: int64

`gender` is already encoded as `0` and `1` — i wll keep as-is.

`age` is in age group strings (e.g., `'65-74 years'`, `'above 90'`) — we’ll convert this into ordinal or numeric features.

In [86]:
age_order = {
    '18-24 years': 0,
    '25-34 years': 1,
    '35-44 years': 2,
    '45-54 years': 3,
    '55-64 years': 4,
    '65-74 years': 5,
    '75-84 years': 6,
    '85-89 years': 7,
    'above 90': 8
}

demo['age'] = demo['age'].map(age_order)


downcast integer columns


In [94]:
demo['age'] = demo['age'].astype('int8')
demo['gender'] = demo['gender'].astype('int8') 

In [96]:
demo.to_parquet("new_sample_one_processed/processed_cultures_demographics.parquet", index=False)
print(f"The processed_cultures_demographics.parquet is saved :)")

The processed_cultures_demographics.parquet is saved :)


## check processed_cultures_demographics.parquet file

In [174]:
import pandas as pd
demo = pd.read_parquet("new_sample_one_processed/processed_cultures_demographics.parquet")
demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4875 entries, 0 to 4874
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   anon_id               4875 non-null   object
 1   pat_enc_csn_id_coded  4875 non-null   int64 
 2   order_proc_id_coded   4875 non-null   int64 
 3   age                   4875 non-null   int8  
 4   gender                4875 non-null   int8  
dtypes: int64(2), int8(2), object(1)
memory usage: 123.9+ KB


## antibiotic_class_exposure.parquet file preparing 

In [54]:
import pandas as pd
class_df = pd.read_parquet("new_sample_one/antibiotic_class_exposure.parquet")
class_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63174 entries, 0 to 63173
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  63174 non-null  object
 1   pat_enc_csn_id_coded     63174 non-null  int64 
 2   order_proc_id_coded      63174 non-null  int64 
 3   order_time_jittered_utc  63174 non-null  object
 4   medication_category      63174 non-null  object
 5   medication_name          63174 non-null  object
 6   antibiotic_class         63174 non-null  object
 7   time_to_culturetime      63174 non-null  Int64 
dtypes: Int64(1), int64(2), object(5)
memory usage: 3.9+ MB


In [56]:
class_df['antibiotic_class'].value_counts()

antibiotic_class
Beta Lactam                   23370
Fluoroquinolone               11276
Macrolide Lincosamide          6364
Combination Antibiotic         6118
Nitrofuran                     3678
Nitroimidazole                 3026
Ansamycin                      1981
Glycopeptide                   1942
Tetracycline                   1530
Oxazolidinone                  1134
Aminoglycoside                  851
Polymyxin, Lipopeptide          405
Urinary Antiseptic              377
Monobactam                      368
Fosfomycin                      318
Sulfonamide                     227
Folate Synthesis Inhibitor      116
Antitubercular                   93
Name: count, dtype: int64

Keeps only useful columns: `anon_id`, `pat_enc_csn_id_coded`, `order_proc_id_coded`, `order_time_jittered_utc`, `antibiotic_class`, `time_to_culturetime`.

Drops redundant ones: `medication_name`, `medication_category`.

Filters to only exposures within the last 365 days (biologically relevant).

In [59]:
import pandas as pd

class_df = class_df.drop(columns=[
    "medication_name",      
    "medication_category" 
])

class_df = class_df[class_df["time_to_culturetime"] <= 365]

print(class_df.info())


<class 'pandas.core.frame.DataFrame'>
Index: 19818 entries, 4 to 63170
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  19818 non-null  object
 1   pat_enc_csn_id_coded     19818 non-null  int64 
 2   order_proc_id_coded      19818 non-null  int64 
 3   order_time_jittered_utc  19818 non-null  object
 4   antibiotic_class         19818 non-null  object
 5   time_to_culturetime      19818 non-null  Int64 
dtypes: Int64(1), int64(2), object(3)
memory usage: 1.1+ MB
None


Check Value Distribution `antibiotic_class`

In [62]:
class_df['antibiotic_class'].value_counts()


antibiotic_class
Beta Lactam                   7264
Fluoroquinolone               3562
Combination Antibiotic        1820
Macrolide Lincosamide         1754
Nitrofuran                    1041
Nitroimidazole                 928
Ansamycin                      796
Glycopeptide                   679
Tetracycline                   579
Oxazolidinone                  405
Aminoglycoside                 368
Fosfomycin                     164
Urinary Antiseptic             153
Monobactam                     109
Polymyxin, Lipopeptide          69
Sulfonamide                     48
Antitubercular                  48
Folate Synthesis Inhibitor      31
Name: count, dtype: int64

In [64]:
class_counts = class_df['antibiotic_class'].value_counts()
common_classes = class_counts[class_counts >= 100].index

class_df['antibiotic_class'] = class_df['antibiotic_class'].apply(
    lambda x: x if x in common_classes else 'other'
)


Convert to Category + Encode

In [67]:
class_df['antibiotic_class'] = class_df['antibiotic_class'].astype('category')
class_df['antibiotic_class'] = class_df['antibiotic_class'].cat.codes


In [69]:
class_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19818 entries, 4 to 63170
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  19818 non-null  object
 1   pat_enc_csn_id_coded     19818 non-null  int64 
 2   order_proc_id_coded      19818 non-null  int64 
 3   order_time_jittered_utc  19818 non-null  object
 4   antibiotic_class         19818 non-null  int8  
 5   time_to_culturetime      19818 non-null  Int64 
dtypes: Int64(1), int64(2), int8(1), object(2)
memory usage: 967.7+ KB


In [71]:
class_df.to_parquet("new_sample_one_processed/processed_antibiotic_class_exposure.parquet", index=False)
print(f"The processed_antibiotic_class_exposure.parquet is saved :)")

The processed_antibiotic_class_exposure.parquet is saved :)


## check antibiotic_class_exposure.parquet 

In [74]:
import pandas as dp

class_df = pd.read_parquet("new_sample_one_processed/processed_antibiotic_class_exposure.parquet")
class_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19818 entries, 0 to 19817
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   anon_id                  19818 non-null  object
 1   pat_enc_csn_id_coded     19818 non-null  int64 
 2   order_proc_id_coded      19818 non-null  int64 
 3   order_time_jittered_utc  19818 non-null  object
 4   antibiotic_class         19818 non-null  int8  
 5   time_to_culturetime      19818 non-null  Int64 
dtypes: Int64(1), int64(2), int8(1), object(2)
memory usage: 813.0+ KB


## antibiotic_subtype_exposure.parquet file preparing 

In [79]:
import pandas as pd
subtype_df = pd.read_parquet("new_sample_one/antibiotic_subtype_exposure.parquet")
subtype_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63174 entries, 0 to 63173
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   anon_id                         63174 non-null  object
 1   pat_enc_csn_id_coded            63174 non-null  int64 
 2   order_proc_id_coded             63174 non-null  int64 
 3   order_time_jittered_utc         63174 non-null  object
 4   medication_category             63174 non-null  object
 5   medication_name                 63174 non-null  object
 6   antibiotic_subtype              63174 non-null  object
 7   antibiotic_subtype_category     63174 non-null  object
 8   medication_time_to_cultureTime  63174 non-null  Int64 
dtypes: Int64(1), int64(2), object(6)
memory usage: 4.4+ MB


In [81]:
subtype_df['antibiotic_subtype_category'].value_counts()

antibiotic_subtype_category
CEP1    11301
FLQ     11276
BLC      7964
SULC     6118
MAC      4923
NIT      3678
NIM      3026
ANS      1981
GLY      1942
CEP3     1745
TET      1530
PEN      1445
LIN      1441
OXA      1134
AMG       851
CAR       510
POL       405
UA        377
MON       368
FOS       318
CEP2      268
SUL       227
CEP4      137
FSI       116
AT         93
Name: count, dtype: int64

In [83]:
subtype_df['antibiotic_subtype'].value_counts()

antibiotic_subtype
Cephalosporin Gen1            11301
Fluoroquinolone               11276
Beta Lactam Combo              7964
Sulfonamide Combo              6118
Macrolide                      4923
Nitrofuran                     3678
Nitroimidazole                 3026
Ansamycin                      1981
Glycopeptide                   1942
Cephalosporin Gen3             1745
Tetracycline                   1530
Penicillin                     1445
Lincosamide                    1441
Oxazolidinone                  1134
Aminoglycoside                  851
Carbapenem                      510
Polymyxin                       405
Urinary Antiseptic              377
Monobactam                      368
Fosfomycin                      318
Cephalosporin Gen2              268
Sulfonamide                     227
Cephalosporin Gen4              137
Folate Synthesis Inhibitor      116
Antitubercular                   93
Name: count, dtype: int64

`antibiotic_subtype`:
Useful. Captures granular details of prior antibiotic exposure (e.g., *Cephalosporin Gen1*, *Fluoroquinolone*), which may help identify specific resistance patterns that broader classes cannot. Important for understanding generation-specific effects (e.g., *Gen1* vs. *Gen3* cephalosporins).

`antibiotic_subtype_category`:
Redundant with `antibiotic_subtype` (e.g., *FLQ* maps to *Fluoroquinolone*). I will drop it.

`time_to_culturetime`:
Important for differentiating recent vs. historical exposure, which may affect resistance likelihood.

`medication_name` and `medication_category`:
Likely redundant — already handled in `prior_med.parquet`.

In [86]:
# Drop redundant columns
subtype_df = subtype_df.drop(columns=[
    "medication_name",               # Redundant: already handled in prior_med
    "medication_category",           # Redundant
    "antibiotic_subtype_category"    # Redundant with antibiotic_subtype
])

print(subtype_df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63174 entries, 0 to 63173
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   anon_id                         63174 non-null  object
 1   pat_enc_csn_id_coded            63174 non-null  int64 
 2   order_proc_id_coded             63174 non-null  int64 
 3   order_time_jittered_utc         63174 non-null  object
 4   antibiotic_subtype              63174 non-null  object
 5   medication_time_to_cultureTime  63174 non-null  Int64 
dtypes: Int64(1), int64(2), object(3)
memory usage: 3.0+ MB
None


In [88]:
subtype_df['antibiotic_subtype'].value_counts()

antibiotic_subtype
Cephalosporin Gen1            11301
Fluoroquinolone               11276
Beta Lactam Combo              7964
Sulfonamide Combo              6118
Macrolide                      4923
Nitrofuran                     3678
Nitroimidazole                 3026
Ansamycin                      1981
Glycopeptide                   1942
Cephalosporin Gen3             1745
Tetracycline                   1530
Penicillin                     1445
Lincosamide                    1441
Oxazolidinone                  1134
Aminoglycoside                  851
Carbapenem                      510
Polymyxin                       405
Urinary Antiseptic              377
Monobactam                      368
Fosfomycin                      318
Cephalosporin Gen2              268
Sulfonamide                     227
Cephalosporin Gen4              137
Folate Synthesis Inhibitor      116
Antitubercular                   93
Name: count, dtype: int64

## Convert antibiotic_subtype to category and encode

In [91]:
subtype_df['antibiotic_subtype'] = subtype_df['antibiotic_subtype'].astype('category')
subtype_df['antibiotic_subtype'] = subtype_df['antibiotic_subtype'].cat.codes

In [93]:
subtype_df.to_parquet("new_sample_one_processed/processed_antibiotic_subtype_exposure.parquet", index=False)
print(f"The processed_antibiotic_subtype_exposure.parquet is saved :)")

The processed_antibiotic_subtype_exposure.parquet is saved :)


## check antibiotic_subtype_exposure.parquet file

In [97]:
import pandas as dp

class_df = pd.read_parquet("new_sample_one_processed/processed_antibiotic_subtype_exposure.parquet")
class_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63174 entries, 0 to 63173
Data columns (total 6 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   anon_id                         63174 non-null  object
 1   pat_enc_csn_id_coded            63174 non-null  int64 
 2   order_proc_id_coded             63174 non-null  int64 
 3   order_time_jittered_utc         63174 non-null  object
 4   antibiotic_subtype              63174 non-null  int8  
 5   medication_time_to_cultureTime  63174 non-null  Int64 
dtypes: Int64(1), int64(2), int8(1), object(2)
memory usage: 2.5+ MB


## cultures_comorbidity.parquet file preparing

In [230]:
import pandas as pd
como = pd.read_parquet("new_sample_one/cultures_comorbidity.parquet")
como.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2277646 entries, 0 to 2277645
Data columns (total 7 columns):
 #   Column                                    Dtype  
---  ------                                    -----  
 0   anon_id                                   object 
 1   pat_enc_csn_id_coded                      int64  
 2   order_proc_id_coded                       int64  
 3   order_time_jittered_utc                   object 
 4   comorbidity_component                     object 
 5   comorbidity_component_start_days_culture  Int64  
 6   comorbidity_component_end_days_culture    float32
dtypes: Int64(1), float32(1), int64(2), object(3)
memory usage: 115.1+ MB


wow (2.2M rows) is too large :) 

it likely includes many comorbidity records per patient, possibly across time.

Each row likely means:
“This patient had comorbidity X active between X and Y days relative to the culture.”

This allows temporally aware features, but also means:
- I must aggregate it per culture.
- Raw format is not usable as-is.

Steps: 

1. Filter: Keep only comorbidities active at or before the culture date.

    - comorbidity_component_start_days_culture <= 0

    - AND (either no end or ends after culture): comorbidity_component_end_days_culture >= 0 or NaN

2. Pivot: Turn the long table into one row per order_proc_id_coded with binary flags:

3. I will drop very rare comorbidities (<1%) :).

In [245]:
print(f'Max comorbidity_component_start_days_culture = {como["comorbidity_component_start_days_culture"].max()}')
print(f'Min comorbidity_component_start_days_culture = {como["comorbidity_component_start_days_culture"].min()}')
print(f'Max comorbidity_component_end_days_culture = {como["comorbidity_component_end_days_culture"].max()}')
print(f'Min comorbidity_component_end_days_culture = {como["comorbidity_component_end_days_culture"].min()}')

Max comorbidity_component_start_days_culture = 7891
Min comorbidity_component_start_days_culture = 0
Max comorbidity_component_end_days_culture = 5565.0
Min comorbidity_component_end_days_culture = -5013.0


- Some comorbidities start years after the culture (max start = 7891 days).
- Others end years before culture (min end = –5013 days).
Still makes perfect sense :) — it selects only comorbidities that were:

Still makes perfect sense ✅ — it selects only comorbidities that were:
- Already active on or before the culture (start_days <= 0)
- And still ongoing at culture time (end_days >= 0 or unknown)
These are the comorbidities most likely to influence resistance at the time of infection.


In [253]:
como['comorbidity_component'].value_counts()

comorbidity_component
Congestive heart failure                                                      230026
Other specified status                                                         60619
Abnormal findings without diagnosis                                            57061
Organ transplant status                                                        52370
Personal/family history of disease                                             49741
                                                                               ...  
Encounter for mental health conditions                                             3
OB-related trauma to perineum and vulva                                            3
Perinatal infections                                                               2
Obstetric history affecting care in pregnancy                                      2
Newborn affected by maternal conditions or complications of labor/delivery         1
Name: count, Length: 466, dtype: int64

As i said befor i will drop Rare Comorbidities
I should drop any comorbidity present in <1% of rows. This:
- Removes noise
- Reduces dimensionality
- Keeps only conditions likely to generalize in your model


In [257]:
import pandas as pd

active_como = como[
    (como["comorbidity_component_start_days_culture"] <= 0) &
    (
        (como["comorbidity_component_end_days_culture"].isna()) |
        (como["comorbidity_component_end_days_culture"] >= 0)
    )
]

# Step 2: Pivot to get binary indicators per comorbidity
# Each comorbidity becomes a column: 1 if present, 0 if not
pivot_como = (
    active_como
    .drop_duplicates(subset=["order_proc_id_coded", "comorbidity_component"])
    .assign(value=1)
    .pivot(index="order_proc_id_coded", columns="comorbidity_component", values="value")
    .fillna(0)
    .astype("int8")
    .reset_index()
)

# Step 3: Drop very rare comorbidities (<1% prevalence)
n_rows = pivot_como.shape[0]
threshold = int(n_rows * 0.01)

# Keep only columns with at least 1% non-zero values
common_como_cols = [
    col for col in pivot_como.columns[1:]  # skip index col
    if pivot_como[col].sum() >= threshold
]

# Final cleaned dataset
pivot_como_filtered = pivot_como[["order_proc_id_coded"] + common_como_cols]


In [259]:
print("Final shape:", pivot_como_filtered.shape)
print("Kept comorbidities:", common_como_cols)


Final shape: (4554, 175)
Kept comorbidities: ['Abdominal hernia', 'Abdominal pain and other digestive/abdomen signs and symptoms', 'Abnormal findings without diagnosis', 'Acquired absence of limb or organ', 'Acute and unspecified renal failure', 'Acute hemorrhagic cerebrovascular disease', 'Acute myocardial infarction', 'Acute phlebitis; thrombophlebitis and thromboembolism', 'Adverse effects of drugs and medicaments, initial encounter', 'Alcohol-related disorders', 'Anxiety and fear-related disorders', 'Aplastic anemia', 'Aspiration pneumonitis', 'Asthma', 'Bacterial infections', 'Benign neoplasms', 'Biliary tract disease', 'Blindness and vision defects', 'Breast cancer - all other types', 'Calculus of urinary tract', 'Cardiac arrhythmias', 'Cardiac dysrhythmias', 'Cerebral infarction', 'Chronic kidney disease', 'Chronic obstructive pulmonary disease and bronchiectasis', 'Chronic pulmonary disease', 'Chronic rheumatic heart disease', 'Circulatory signs and symptoms', 'Coagulation and 

OMG i am crying 😭 right now. Allah Al-must3an.

Let’s Reduce the Comorbidities Now (Clean + Efficient)
I’ll simplify by:

- Step 1: Identify most common clinically relevant comorbidities (e.g., diabetes, CHF, CKD, cancer, transplant).
- Step 2: Group similar/related conditions under umbrella terms.
- Step 3: Create a small set of binary flags (10–20 max).

### ✅ Reduced Comorbidity Feature Groupings

| Feature Name             | Description / Included Conditions                                      |
|--------------------------|------------------------------------------------------------------------|
| `has_diabetes`           | Diabetes mellitus (Type 1 or 2), insulin dependence                    |
| `has_chf`                | Congestive heart failure, chronic heart failure                        |
| `has_ckd`                | Chronic kidney disease, renal failure                                  |
| `has_cancer`             | Solid tumors, hematologic malignancies (e.g., leukemia, lymphoma)      |
| `has_transplant`         | History of organ or bone marrow transplant                             |
| `has_immunosuppression`  | HIV/AIDS, immunodeficiency syndromes, long-term immunosuppressive meds |
| `has_copd`               | Chronic obstructive pulmonary disease, chronic bronchitis, emphysema   |
| `has_liver_disease`      | Cirrhosis, hepatitis, liver failure                                    |
| `has_dementia`           | Alzheimer’s disease, vascular dementia                                 |
| `has_stroke`             | Stroke, cerebrovascular accident (CVA), residual deficits              |
| `has_other_comorbid`     | Any other less frequent or uncategorized comorbidity                   |

Zero energy.
Yarb :(.

In [274]:
import pandas as pd
import numpy as np

# Load raw comorbidity file
como = pd.read_parquet("new_sample_one/cultures_comorbidity.parquet")

# Filter active at culture time
active_como = como[
    (como["comorbidity_component_start_days_culture"] <= 0) &
    (
        (como["comorbidity_component_end_days_culture"].isna()) |
        (como["comorbidity_component_end_days_culture"] >= 0)
    )
].copy()

# Define mapping from component to new grouped feature
group_mapping = {
    "has_diabetes": ["diabetes"],
    "has_chf": ["heart failure"],
    "has_ckd": ["chronic kidney", "renal failure"],
    "has_cancer": ["malignancy", "cancer", "neoplasm", "leukemia", "lymphoma"],
    "has_transplant": ["transplant"],
    "has_immunosuppression": ["hiv", "immunodeficiency", "immunosuppress", "long-term (current) drug therapy"],
    "has_copd": ["copd", "chronic obstructive", "emphysema", "chronic bronchitis"],
    "has_liver_disease": ["cirrhosis", "liver", "hepatitis"],
    "has_dementia": ["dementia", "alzheimer"],
    "has_stroke": ["stroke", "cerebrovascular", "cva"],
}

# Normalize component text for matching
active_como["component_clean"] = active_como["comorbidity_component"].str.lower()

# Create binary flags based on keyword matching
grouped_flags = []
for new_col, keywords in group_mapping.items():
    mask = active_como["component_clean"].apply(lambda x: any(k in x for k in keywords))
    matched = active_como[mask][["order_proc_id_coded"]].drop_duplicates()
    matched[new_col] = 1
    grouped_flags.append(matched)

# Combine all flags into one dataframe
reduced_como = pd.DataFrame({"order_proc_id_coded": active_como["order_proc_id_coded"].unique()})
for df in grouped_flags:
    reduced_como = reduced_como.merge(df, on="order_proc_id_coded", how="left")

# Fill NaNs with 0 (i.e., patient didn't have that comorbidity)
reduced_como = reduced_como.fillna(0).astype({col: 'int8' for col in reduced_como.columns if col != "order_proc_id_coded"})

# Add "has_other_comorbid" if any unmatched component exists
matched_ids = pd.concat(grouped_flags)["order_proc_id_coded"].unique()
all_ids = active_como["order_proc_id_coded"].unique()
unmatched_ids = set(all_ids) - set(matched_ids)

reduced_como["has_other_comorbid"] = reduced_como["order_proc_id_coded"].isin(unmatched_ids).astype("int8")


In [276]:
print("Reduced shape:", reduced_como.shape)
print("Columns:", reduced_como.columns.tolist())


Reduced shape: (4554, 12)
Columns: ['order_proc_id_coded', 'has_diabetes', 'has_chf', 'has_ckd', 'has_cancer', 'has_transplant', 'has_immunosuppression', 'has_copd', 'has_liver_disease', 'has_dementia', 'has_stroke', 'has_other_comorbid']


In [278]:
reduced_como.to_parquet("new_sample_one_processed/processed_cultures_comorbidity.parquet", index=False)
print(f"The processed_cultures_comorbidity.parquet is saved :)")

The processed_cultures_comorbidity.parquet is saved :)


## check cultures_comorbidity.parquet file

In [4]:
import pandas as pd
como = pd.read_parquet("new_sample_one_processed/processed_cultures_comorbidity.parquet")
como.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4554 entries, 0 to 4553
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_proc_id_coded    4554 non-null   int64
 1   has_diabetes           4554 non-null   int8 
 2   has_chf                4554 non-null   int8 
 3   has_ckd                4554 non-null   int8 
 4   has_cancer             4554 non-null   int8 
 5   has_transplant         4554 non-null   int8 
 6   has_immunosuppression  4554 non-null   int8 
 7   has_copd               4554 non-null   int8 
 8   has_liver_disease      4554 non-null   int8 
 9   has_dementia           4554 non-null   int8 
 10  has_stroke             4554 non-null   int8 
 11  has_other_comorbid     4554 non-null   int8 
dtypes: int64(1), int8(11)
memory usage: 84.6 KB


-----
Some files like `prior_infecting_organism`, `nursing_home_visits`, and `adi_scores` could improve prediction — especially if I targete high resistance risk.

Files like `implied_susceptibility` and `microbial_resistance` might be label-related.

`cultures_priorprocedures` and `ward_info` are likely optional unless I want hospital-level factors.

For now, I will do a merge and test if I get terrible results I will come back and complete the rest.


## Merge

In [1]:
import dask.dataframe as dd
import os

linked_features = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']

files_info_processed = [
    {
        "name": "processed_cultures_cohort",
        "path": "microbiology_cultures_cohort.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "order_time_jittered_utc":"object",
            "organism": "int8",
            "antibiotic": "int8",
            "susceptibility": "int8"
        }
    },
    {
        "name": "processed_prior_med",
        "path": "microbiology_cultures_prior_med.csv",
        "merge_on": linked_features,
        "dtype": {
             "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "medication_time_to_culturetime": "Int64", 
            "medication_category": "int8",
            "med_within_30_days": "boolean"
        }
    },
    {
        "name": "processed_cultures_demographics",
        "path": "microbiology_cultures_demographics.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "age": "int8",
            "gender": "int8"
        }
    },
     {
        "name": "processed_cultures_labs",
        "path": "microbiology_cultures_labs.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_wbc": "float32",
            "median_neutrophils": "float32",
            "median_lymphocytes": "float32",
            "median_hgb": "float32",
            "median_plt": "float32",
            "median_na": "float32",
            "median_hco3": "float32",
            "median_bun": "float32",
            "median_cr": "float32",
            "median_lactate": "float32",
            "median_procalcitonin": "float32",
            "delta_wbc": "float32",
            "delta_na": "float32",
            "delta_hco3": "float32",
            "delta_bun": "float32",
            "delta_cr": "float32"
        }
    },
    {
        "name": "processed_cultures_vitals",
        "path": "microbiology_cultures_vitals.csv",
        "merge_on": linked_features[:3],
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_heartrate": "float32",
            "median_resprate": "float32",
            "median_temp": "float32",
            "median_sysbp": "float32",
            "median_diasbp": "float32",
            "delta_heartrate": "float32",
            "delta_resprate": "float32",
            "delta_temp": "float32",
            "delta_sysbp": "float32",
            "delta_diasbp": "float32"
        }
    },
     {
        "name": "processed_antibiotic_class_exposure",
        "path": "microbiology_cultures_antibiotic_class_exposure.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "antibiotic_class": "int8",
            "time_to_culturetime": "Int64"  
        }
    },
    {
    "name": "processed_antibiotic_subtype_exposure",
    "path": "microbiology_cultures_antibiotic_subtype_exposure.csv",
    "merge_on": ["anon_id", "pat_enc_csn_id_coded", "order_proc_id_coded", "order_time_jittered_utc"],
    "dtype": {
        "anon_id": "object",
        "pat_enc_csn_id_coded": "int64",
        "order_proc_id_coded": "int64",
        "order_time_jittered_utc": "object",
        "antibiotic_subtype": "int8",
        "medication_time_to_cultureTime": "Int64"  
        }
    },
    # {
    #     "name": "processed_prior_infecting_organism",
    #     "path": "microbiology_culture_prior_infecting_organism.csv",
    #     "merge_on": linked_features, 
    #     "dtype": {
    #         "prior_organism": "object",
    #         "prior_infecting_organism_days_to_culutre": "Int64"
    #     }
    # },
    {
    "name": "processed_cultures_comorbidity",
    "path": "microbiology_cultures_comorbidity.csv",
    "merge_on": ["order_proc_id_coded"], 
    "dtype": {
        "order_proc_id_coded": "int64",
        "has_diabetes": "int8",
        "has_chf": "int8",
        "has_ckd": "int8",
        "has_cancer": "int8",
        "has_transplant": "int8",
        "has_immunosuppression": "int8",
        "has_copd": "int8",
        "has_liver_disease": "int8",
        "has_dementia": "int8",
        "has_stroke": "int8",
        "has_other_comorbid": "int8"
    }
}

]

sample_folder = 'new_sample_one_processed/'
merged_folder = 'merged_sample_one_processed/'
os.makedirs(merged_folder, exist_ok=True)         

file_df_pairs = [file['name'] + '.parquet' for file in files_info_processed]

based_df_dtype = files_info_processed[0]['dtype']
df_dtype = files_info_processed[1]['dtype']

based_df = dd.read_parquet(sample_folder + file_df_pairs[0], 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[1], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[0]['merge_on'])

print(f"Starrt merging: left {files_info_processed[0]['name']}.parquet ; right {files_info_processed[1]['name']}.parquet")

based_df.to_parquet(
            merged_folder,
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left processed_cultures_cohort.parquet ; right processed_prior_med.parquet
Merged result saved - Cols # 10


In [5]:

df_dtype = files_info_processed[2]['dtype']
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[2], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[2]['merge_on'])

print(f"Starrt merging: left Based File ; right {files_info_processed[2]['name']}.parquet")

based_df.to_parquet(
            merged_folder,
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left Based File ; right processed_cultures_demographics.parquet
Merged result saved - Cols # 12


In [7]:

df_dtype = files_info_processed[3]['dtype']
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[3], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[3]['merge_on'])

print(f"Starrt merging: left Based File ; right {files_info_processed[3]['name']}.parquet")

based_df.to_parquet(
            merged_folder,
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left Based File ; right processed_cultures_labs.parquet
Merged result saved - Cols # 28


In [9]:

df_dtype = files_info_processed[4]['dtype']
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[4], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[4]['merge_on'])

print(f"Starrt merging: left Based File ; right {files_info_processed[4]['name']}.parquet")

based_df.to_parquet(
            merged_folder,
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left Based File ; right processed_cultures_vitals.parquet
Merged result saved - Cols # 38


## Chech the merge result until now!

In [12]:
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
num_cols = len(based_df.columns)
num_rows = based_df.shape[0].compute()
print(f"Shape: ({num_rows},{num_cols})")

Shape: (249369,38)


In [14]:

df_dtype = files_info_processed[5]['dtype']
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[5], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[5]['merge_on'])

print(f"Starrt merging: left Based File ; right {files_info_processed[5]['name']}.parquet")

based_df.to_parquet(
            merged_folder,
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left Based File ; right processed_antibiotic_class_exposure.parquet
Merged result saved - Cols # 40


**Because i expect the error from now i will save the result into new file to keep last merge valid**

In [3]:
linked_features = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']

files_info_processed = [
    {
        "name": "processed_cultures_cohort",
        "path": "microbiology_cultures_cohort.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "order_time_jittered_utc":"object",
            "organism": "int8",
            "antibiotic": "int8",
            "susceptibility": "int8"
        }
    },
    {
        "name": "processed_prior_med",
        "path": "microbiology_cultures_prior_med.csv",
        "merge_on": linked_features,
        "dtype": {
             "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "medication_time_to_culturetime": "Int64", 
            "medication_category": "int8",
            "med_within_30_days": "boolean"
        }
    },
    {
        "name": "processed_cultures_demographics",
        "path": "microbiology_cultures_demographics.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "age": "int8",
            "gender": "int8"
        }
    },
     {
        "name": "processed_cultures_labs",
        "path": "microbiology_cultures_labs.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_wbc": "float32",
            "median_neutrophils": "float32",
            "median_lymphocytes": "float32",
            "median_hgb": "float32",
            "median_plt": "float32",
            "median_na": "float32",
            "median_hco3": "float32",
            "median_bun": "float32",
            "median_cr": "float32",
            "median_lactate": "float32",
            "median_procalcitonin": "float32",
            "delta_wbc": "float32",
            "delta_na": "float32",
            "delta_hco3": "float32",
            "delta_bun": "float32",
            "delta_cr": "float32"
        }
    },
    {
        "name": "processed_cultures_vitals",
        "path": "microbiology_cultures_vitals.csv",
        "merge_on": linked_features[:3],
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_heartrate": "float32",
            "median_resprate": "float32",
            "median_temp": "float32",
            "median_sysbp": "float32",
            "median_diasbp": "float32",
            "delta_heartrate": "float32",
            "delta_resprate": "float32",
            "delta_temp": "float32",
            "delta_sysbp": "float32",
            "delta_diasbp": "float32"
        }
    },
     {
        "name": "processed_antibiotic_class_exposure",
        "path": "microbiology_cultures_antibiotic_class_exposure.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "antibiotic_class": "int8",
            "time_to_culturetime": "Int64"  
        }
    },
    {
    "name": "processed_antibiotic_subtype_exposure",
    "path": "microbiology_cultures_antibiotic_subtype_exposure.csv",
    "merge_on": ["anon_id", "pat_enc_csn_id_coded", "order_proc_id_coded", "order_time_jittered_utc"],
    "dtype": {
        "anon_id": "object",
        "pat_enc_csn_id_coded": "int64",
        "order_proc_id_coded": "int64",
        "order_time_jittered_utc": "object",
        "antibiotic_subtype": "int8",
        "medication_time_to_cultureTime": "Int64"  
        }
    },
    # {
    #     "name": "processed_prior_infecting_organism",
    #     "path": "microbiology_culture_prior_infecting_organism.csv",
    #     "merge_on": linked_features, 
    #     "dtype": {
    #         "prior_organism": "object",
    #         "prior_infecting_organism_days_to_culutre": "Int64"
    #     }
    # },
    {
    "name": "processed_cultures_comorbidity",
    "path": "microbiology_cultures_comorbidity.csv",
    "merge_on": ["order_proc_id_coded"], 
    "dtype": {
        "order_proc_id_coded": "int64",
        "has_diabetes": "int8",
        "has_chf": "int8",
        "has_ckd": "int8",
        "has_cancer": "int8",
        "has_transplant": "int8",
        "has_immunosuppression": "int8",
        "has_copd": "int8",
        "has_liver_disease": "int8",
        "has_dementia": "int8",
        "has_stroke": "int8",
        "has_other_comorbid": "int8"
    }
}

]

In [5]:
import dask.dataframe as dd
import os

sample_folder = 'new_sample_one_processed/'
merged_folder = 'merged_sample_one_processed/'
os.makedirs(merged_folder, exist_ok=True)

file_df_pairs = [file['name'] + '.parquet' for file in files_info_processed]

df_dtype = files_info_processed[6]['dtype']
based_df_dtype = {}
for i in range(0 , 6):
    based_df_dtype.update(files_info_processed[i]['dtype'])

df = dd.read_parquet(sample_folder + file_df_pairs[6], dtype=df_dtype)
based_df = dd.read_parquet(merged_folder + "*.parquet", dtype=based_df_dtype)

merge_cols = files_info_processed[6]['merge_on']

df['merge_key'] = df[merge_cols].astype(str).apply(lambda row: '_'.join(row.values), axis=1, meta=('merge_key', 'str'))
based_df['merge_key'] = based_df[merge_cols].astype(str).apply(lambda row: '_'.join(row.values), axis=1, meta=('merge_key', 'str'))

df = df.set_index('merge_key', shuffle='tasks')
based_df = based_df.set_index('merge_key', shuffle='tasks')

based_df = based_df.merge(df, how='left', left_index=True, right_index=True)
based_df = based_df.repartition(partition_size="100MB")

print(f"Starrt merging: left Based File ; right {files_info_processed[6]['name']}.parquet")

based_df.to_parquet(
    merged_folder + 'merge_antibiotic_subtype_exposure',
    engine='pyarrow',
    compression='snappy',
    write_index=False
)

based_df_dtype.update(df_dtype)
print(f"Merged result saved - Cols # {len(based_df.columns)}")


Starrt merging: left Based File ; right processed_antibiotic_subtype_exposure.parquet


ArrowInvalid: Take operation overflowed binary array capacity

In [7]:

df_dtype = files_info_processed[7]['dtype']
based_df = dd.read_parquet(merged_folder +"*.parquet", 
                           dtype = based_df_dtype)
df = dd.read_parquet(sample_folder + file_df_pairs[7], 
                           dtype = df_dtype )

based_df = based_df.merge(df, how='left', on=files_info_processed[7]['merge_on'])

print(f"Starrt merging: left Based File ; right {files_info_processed[7]['name']}.parquet")

based_df.to_parquet(
            merged_folder+'processed_cultures_comorbidity',
            engine='pyarrow',
            compression='snappy',
            write_index=False
        )

based_df_dtype.update(df_dtype)

print(f"Merged result saved - Cols # {len(based_df.columns)}")

Starrt merging: left Based File ; right processed_cultures_comorbidity.parquet
Merged result saved - Cols # 51


In [12]:
import shutil

shutil.move(
    'merged_sample_one_processed/processed_cultures_comorbidity/part.0.parquet',
    'merged_sample_one_processed/merge_all_except_subtype.parquet'
)


'merged_sample_one_processed/merge_all_except_subtype.parquet'

# Modeling Stage:

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_parquet("merged_sample_one_processed/merge_all_except_subtype.parquet")

keys_to_drop = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']
df = df.drop(columns=keys_to_drop, errors='ignore')

target_col = 'susceptibility'
X = df.drop(columns=target_col)
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)


In [3]:
print(X_train.shape)
print(X_test.shape)

(3986113, 46)
(996529, 46)


In [5]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3986113 entries, 3351877 to 2557330
Data columns (total 46 columns):
 #   Column                          Dtype  
---  ------                          -----  
 0   organism                        int8   
 1   antibiotic                      int8   
 2   medication_time_to_culturetime  Int64  
 3   medication_category             float64
 4   med_within_30_days              boolean
 5   age                             int8   
 6   gender                          int8   
 7   median_wbc                      float64
 8   median_neutrophils              float32
 9   median_lymphocytes              float32
 10  median_hgb                      float64
 11  median_plt                      float64
 12  median_na                       float64
 13  median_hco3                     float64
 14  median_bun                      float64
 15  median_cr                       float64
 16  median_lactate                  float64
 17  median_procalcitonin      

All my dataset is nums => ready for modeling 👍.

## Full Modeling Code: XGBoost, LightGBM, CatBoost, and HistGradientBoosting.

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import HistGradientBoostingClassifier


# Helper for results
def evaluate_model(name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        y_prob = model.predict(X_test)  # for CatBoost if predict_proba not available
    print(f"\n🔹 {name}")
    print(classification_report(y_test, y_pred))
    print(f"ROC AUC: {roc_auc_score(y_test, y_prob):.4f}")

# Train and evaluate models
print("Training models...")

xgb_model = XGBClassifier(eval_metric='logloss', tree_method='hist', missing=np.nan,
                          scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum())
xgb_model.fit(X_train, y_train)
evaluate_model("XGBoost", xgb_model, X_test, y_test)

lgb_model = LGBMClassifier()
lgb_model.fit(X_train, y_train)
evaluate_model("LightGBM", lgb_model, X_test, y_test)


cat_model = CatBoostClassifier(verbose=0)

X_train_cat = X_train.astype(object).where(pd.notna(X_train), np.nan)
X_test_cat = X_test.astype(object).where(pd.notna(X_test), np.nan)

cat_model.fit(X_train_cat, y_train)
evaluate_model("CatBoost", cat_model, X_test_cat, y_test)

hgb_model = HistGradientBoostingClassifier()
hgb_model.fit(X_train, y_train)
evaluate_model("HistGradientBoosting", hgb_model, X_test, y_test)


Training models...

🔹 XGBoost
              precision    recall  f1-score   support

         0.0       0.87      0.70      0.78    539542
         1.0       0.71      0.88      0.79    456987

    accuracy                           0.78    996529
   macro avg       0.79      0.79      0.78    996529
weighted avg       0.80      0.78      0.78    996529

ROC AUC: 0.9020
[LightGBM] [Info] Number of positive: 1827947, number of negative: 2158166
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.449074 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2230
[LightGBM] [Info] Number of data points in the train set: 3986113, number of used features: 46
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.458579 -> initscore=-0.166065
[LightGBM] [Info] Start training from score -0.166065

🔹 LightGBM
              precision    recall  f1-score   suppo

## ROC Curve Comparison

The ROC (Receiver Operating Characteristic) curve is a threshold-independent metric that shows the trade-off between true positive rate (recall) and false positive rate across different decision thresholds.

By plotting the ROC curve for each model, we can compare their **ability to rank resistant cases higher than susceptible ones**. The closer the curve is to the top-left corner, the better the model.

The **Area Under the Curve (AUC)** quantifies this performance:
- AUC = 1.0 → Perfect classifier
- AUC = 0.5 → Random guess

Below, we compare the ROC curves of XGBoost, LightGBM, CatBoost, and HistGradientBoosting.


In [21]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

# Compute ROC curve and AUC for each model
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, xgb_model.predict_proba(X_test)[:, 1])
roc_auc_xgb = auc(fpr_xgb, tpr_xgb)

fpr_lgb, tpr_lgb, _ = roc_curve(y_test, lgb_model.predict_proba(X_test)[:, 1])
roc_auc_lgb = auc(fpr_lgb, tpr_lgb)

fpr_cat, tpr_cat, _ = roc_curve(y_test, cat_model.predict_proba(X_test_cat)[:, 1])
roc_auc_cat = auc(fpr_cat, tpr_cat)

fpr_hgb, tpr_hgb, _ = roc_curve(y_test, hgb_model.predict_proba(X_test)[:, 1])
roc_auc_hgb = auc(fpr_hgb, tpr_hgb)

# Plot
plt.figure(figsize=(8, 6))
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {roc_auc_xgb:.4f})")
plt.plot(fpr_lgb, tpr_lgb, label=f"LightGBM (AUC = {roc_auc_lgb:.4f})")
plt.plot(fpr_cat, tpr_cat, label=f"CatBoost (AUC = {roc_auc_cat:.4f})")
plt.plot(fpr_hgb, tpr_hgb, label=f"HistGradientBoosting (AUC = {roc_auc_hgb:.4f})")

plt.plot([0, 1], [0, 1], 'k--', label="Random Classifier")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend(loc="lower right")
plt.grid(True)
plt.tight_layout()
plt.show()


## Modeling Results Summary

In this section, I evaluate and compare the performance of four gradient boosting models on the final merged ARMD dataset: **XGBoost**, **LightGBM**, **CatBoost**, and **HistGradientBoostingClassifier** from scikit-learn. These models were selected due to their robustness to missing data, support for large tabular datasets, and proven performance in binary classification tasks with class imbalance.

The goal is to classify bacterial cultures as **resistant (1)** or **susceptible (0)** to antibiotics based on clinical and demographic features.

---

### XGBoost

XGBoost achieved **the highest ROC AUC score** among all models, making it the most effective at distinguishing resistant cases.

| Metric       | Class 0 (Susceptible) | Class 1 (Resistant) |
|--------------|------------------------|----------------------|
| Precision    | 0.87                   | 0.71                 |
| Recall       | 0.70                   | **0.88** ✅          |
| F1-Score     | 0.78                   | 0.79                 |
| **ROC AUC**  | **0.9020** ✅          |

**Interpretation:**  
XGBoost showed a strong ability to **identify resistant cases**, with a recall of 88% for class 1. While some false positives were present (precision 0.71), the high sensitivity is desirable in a clinical context where missing resistance is riskier than over-treating.

---

### LightGBM

LightGBM provided a more **balanced performance**, with slightly less recall for resistant cases but better performance on the susceptible class.

| Metric       | Class 0 (Susceptible) | Class 1 (Resistant) |
|--------------|------------------------|----------------------|
| Precision    | 0.77                   | 0.80                 |
| Recall       | **0.85** ✅           | 0.70                 |
| F1-Score     | 0.81                   | 0.74                 |
| **ROC AUC**  | 0.8985                 |

**Interpretation:**  
LightGBM leaned toward **avoiding false positives**. It correctly identified 85% of susceptible cases but missed more resistant cases compared to XGBoost. It’s suitable if minimizing unnecessary treatment is a higher priority.

---

### CatBoost

CatBoost delivered **a well-balanced performance**, with metrics very close to LightGBM and a slightly higher ROC AUC.

| Metric       | Class 0 (Susceptible) | Class 1 (Resistant) |
|--------------|------------------------|----------------------|
| Precision    | 0.77                   | 0.79                 |
| Recall       | **0.85** ✅           | 0.71                 |
| F1-Score     | 0.81                   | 0.75                 |
| **ROC AUC**  | **0.9017** ✅          |

**Interpretation:**  
CatBoost offers similar strengths to LightGBM but with **slightly better ranking performance** (ROC AUC). Its built-in support for categorical features and missing values makes it practical and easy to use in healthcare data pipelines.

---

### HistGradientBoostingClassifier

This model is scikit-learn’s native boosting option. Its performance was **nearly identical to LightGBM**, both in metrics and behavior.

| Metric       | Class 0 (Susceptible) | Class 1 (Resistant) |
|--------------|------------------------|----------------------|
| Precision    | 0.77                   | 0.80                 |
| Recall       | **0.85** ✅           | 0.70                 |
| F1-Score     | 0.81                   | 0.74                 |
| **ROC AUC**  | 0.8985                 |

**Interpretation:**  
A reliable, fast baseline that performs well on structured data. Offers strong performance without additional libraries, useful in minimal setups.

---

### Conclusion

All four models performed well, with **ROC AUC scores near or above 0.90**, indicating **excellent discrimination** between resistant and susceptible cases.  
However:

- **XGBoost is the best choice** when the priority is to catch as many resistant infections as possible (high recall).
- **CatBoost is nearly as strong**, and provides a good balance.
- **LightGBM and HGBClassifier** are more conservative and slightly better at reducing false positives.

These results validate the modeling pipeline and demonstrate that ensemble tree-based methods are effective for antibiotic resistance prediction using EHR-derived features.


-------

----

In [1]:
import dask.dataframe as dd
import os

linked_features = ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered_utc']

files_info_processed = [
    {
        "name": "processed_cultures_cohort",
        "path": "microbiology_cultures_cohort.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "order_time_jittered_utc":"object",
            "organism": "int8",
            "antibiotic": "int8",
            "susceptibility": "int8"
        }
    },
    {
        "name": "processed_prior_med",
        "path": "microbiology_cultures_prior_med.csv",
        "merge_on": linked_features,
        "dtype": {
             "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "medication_time_to_culturetime": "Int64", 
            "medication_category": "int8",
            "med_within_30_days": "boolean"
        }
    },
    {
        "name": "processed_cultures_demographics",
        "path": "microbiology_cultures_demographics.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id":"object",
            "pat_enc_csn_id_coded":"int64",
            "order_proc_id_coded":"int64 ",
            "age": "int8",
            "gender": "int8"
        }
    },
     {
        "name": "processed_cultures_labs",
        "path": "microbiology_cultures_labs.csv",
        "merge_on": linked_features[:3], 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_wbc": "float32",
            "median_neutrophils": "float32",
            "median_lymphocytes": "float32",
            "median_hgb": "float32",
            "median_plt": "float32",
            "median_na": "float32",
            "median_hco3": "float32",
            "median_bun": "float32",
            "median_cr": "float32",
            "median_lactate": "float32",
            "median_procalcitonin": "float32",
            "delta_wbc": "float32",
            "delta_na": "float32",
            "delta_hco3": "float32",
            "delta_bun": "float32",
            "delta_cr": "float32"
        }
    },
    {
        "name": "processed_cultures_vitals",
        "path": "microbiology_cultures_vitals.csv",
        "merge_on": linked_features[:3],
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "median_heartrate": "float32",
            "median_resprate": "float32",
            "median_temp": "float32",
            "median_sysbp": "float32",
            "median_diasbp": "float32",
            "delta_heartrate": "float32",
            "delta_resprate": "float32",
            "delta_temp": "float32",
            "delta_sysbp": "float32",
            "delta_diasbp": "float32"
        }
    },
     {
        "name": "processed_antibiotic_class_exposure",
        "path": "microbiology_cultures_antibiotic_class_exposure.csv",
        "merge_on": linked_features, 
        "dtype": {
            "anon_id": "object",
            "pat_enc_csn_id_coded": "int64",
            "order_proc_id_coded": "int64",
            "order_time_jittered_utc": "object",
            "antibiotic_class": "int8",
            "time_to_culturetime": "Int64"  
        }
    },
    {
    "name": "processed_antibiotic_subtype_exposure",
    "path": "microbiology_cultures_antibiotic_subtype_exposure.csv",
    "merge_on": ["anon_id", "pat_enc_csn_id_coded", "order_proc_id_coded", "order_time_jittered_utc"],
    "dtype": {
        "anon_id": "object",
        "pat_enc_csn_id_coded": "int64",
        "order_proc_id_coded": "int64",
        "order_time_jittered_utc": "object",
        "antibiotic_subtype": "int8",
        "medication_time_to_cultureTime": "Int64"  
        }
    },
    # {
    #     "name": "processed_prior_infecting_organism",
    #     "path": "microbiology_culture_prior_infecting_organism.csv",
    #     "merge_on": linked_features, 
    #     "dtype": {
    #         "prior_organism": "object",
    #         "prior_infecting_organism_days_to_culutre": "Int64"
    #     }
    # },
    {
    "name": "processed_cultures_comorbidity",
    "path": "microbiology_cultures_comorbidity.csv",
    "merge_on": ["order_proc_id_coded"],  # Since only this column is present from the key columns
    "dtype": {
        "order_proc_id_coded": "int64",
        "has_diabetes": "int8",
        "has_chf": "int8",
        "has_ckd": "int8",
        "has_cancer": "int8",
        "has_transplant": "int8",
        "has_immunosuppression": "int8",
        "has_copd": "int8",
        "has_liver_disease": "int8",
        "has_dementia": "int8",
        "has_stroke": "int8",
        "has_other_comorbid": "int8"
    }
}

]

sample_folder = 'new_sample_one_processed/'
merged_folder = 'merged_sample_one_processed/'
os.makedirs(merged_folder, exist_ok=True)

def getMergOn(file):
    for f in files_info_processed:
        if f['name'] == file:
            return f['merge_on']


file_df_pairs = [(file['name'], dd.read_parquet(
    os.path.join(sample_folder, file['name'] + '.parquet'),
    dtype=file['dtype'])) for file in files_info_processed]

# base file
merged_df = file_df_pairs[0][1]
print(f"Load base file: {file_df_pairs[0][0]}")


# Merge sequentially
for file_name, df in file_df_pairs[1:]:
    print(f"Merging file: {file_name}")
    merg_on = getMergOn(file_name)
    merged_df = merged_df.merge(df, how='left', on=merg_on)


# Write to parquet
output_path = os.path.join(merged_folder, 'merged_result.parquet')
merged_df = merged_df.repartition(partition_size="50MB")  # or npartitions=500
# merged_df = merged_df.persist()  # only if RAM allows
print(f"\nWriting merged data to: {output_path}")
write_task = merged_df.to_parquet(
    output_path,
    engine='pyarrow',
    compression='snappy',
    write_index=False,
    write_metadata_file=False,
    compute=False
)
print(f"\n Alhamdulillah the {output_path} merged and saved ✅")
# yarb yshteghel ana t3ebt :(


Load base file: processed_cultures_cohort
Merging file: processed_prior_med
Merging file: processed_cultures_demographics
Merging file: processed_cultures_labs
Merging file: processed_cultures_vitals
Merging file: processed_antibiotic_class_exposure
Merging file: processed_antibiotic_subtype_exposure
Merging file: processed_cultures_comorbidity

Writing merged data to: merged_sample_one_processed/merged_result.parquet


ArrowInvalid: Take operation overflowed binary array capacity

In [3]:
# Actually this is my first merge code, I wrote it on my own but the files are too large so 
# It always rais a memory error.
# I will not delete it because I work hard on it :(.
# + I know it has some logical error :(.
import pandas as pd
import os
import pyarrow as pa
import pyarrow.parquet as pq
import dask as d


sample_folder = 'new_sample_one/'
merged_folder = 'merged_sample_one/'

os.makedirs(merged_folder, exist_ok=True)

merged_dtype = files_info[0]['dtype']
base_sample = pd.read_parquet(sample_folder + files_info[0]['name'] + '.parquet', engine='pyarrow')
base_sample = base_sample.astype(merged_dtype)

print(f"Base file: {sample_folder + files_info[0]['name'] + '.parquet'} is loaded")

def get_df_size_mb(df):
    return df.memory_usage(deep=True).sum() / (1024 ** 2)

def getDatatype(file):
    all_keys = {'anon_id':'object',
               'pat_enc_csn_id_coded':'Int64',
               'order_proc_id_coded':'Int64',
               'order_time_jittered_utc':'object'}
    part_keys = {
                'anon_id':'object',
               'pat_enc_csn_id_coded':'Int64',
               'order_proc_id_coded':'Int64'
    }
    for f in files_info:
        if f['name']== file:
            if len(f['merge_on']) == 4:
                all_keys.update(f['dtype'])
                return all_keys
            else:
                part_keys.update(f['dtype'])
                return part_keys


MAX_MEMORY_MB = 100
mode = 'w'
full = False

for file in files_info[1:]:
    print(f"Start merge with: {sample_folder + file['name'] + '.parquet'} ")
    df = pd.read_parquet(sample_folder + file['name'] + '.parquet' )
    dtype = getDatatype(file['name'])
    merged_dtype.update(dtype)
    df = df.astype(dtype)
    if get_df_size_mb(base_sample) < MAX_MEMORY_MB and not full: 
        base_sample = base_sample.merge(df, how = 'inner', on = file['merge_on'] , suffixes=('', '_right'))
        base_sample = base_sample.drop(columns=[col for col in base_sample.columns if col.endswith('_right')])
        base_sample.to_parquet(merged_folder + 'merged_ARMD.parquet' , engine='pyarrow', index=False)
    else: 
        full = True
        base_sample = pd.DataFrame()
         
    if full: 
        parquet_file = pq.ParquetFile(merged_folder + 'merged_ARMD.parquet')
        for i in range(parquet_file.num_row_groups):
            chunk = parquet_file.read_row_group(i).to_pandas()
            temp = chunk.merge(df, how = 'inner', on = file['merge_on'], suffixes=('', '_right') )
            temp = temp.drop(columns=[col for col in temp.columns if col.endswith('_right')])
            temp = temp.astype(merged_dtype)
            if mode == 'w':
                temp.to_parquet(merged_folder + 'temp_merged_ARMD.parquet', engine = 'pyarrow')
                mode = 'a'
            else:
                temp.to_parquet(merged_folder + 'temp_merged_ARMD.parquet')
                
        mode = 'w'
        
        parquet_file = pq.ParquetFile(merged_folder + 'temp_merged_ARMD.parquet')
        for i in range(parquet_file.num_row_groups):
            chunk = parquet_file.read_row_group(i).to_pandas() 
            chunk = chunk.astype(merged_dtype)
            if mode == 'w':
                temp.to_parquet(merged_folder + 'merged_ARMD.parquet', engine = 'pyarrow')
                mode = 'a'
            else:
                temp.to_parquet(merged_folder + 'merged_ARMD.parquet')
               
print("The merge is done Alhamdulillah :) ")          

Base file: new_sample_one/cultures_cohort.parquet is loaded
Start merge with: new_sample_one/ward_info.parquet 
Start merge with: new_sample_one/prior_med.parquet 
Start merge with: new_sample_one/microbial_resistance.parquet 
Start merge with: new_sample_one/cultures_demographics.parquet 
Start merge with: new_sample_one/cultures_labs.parquet 
Start merge with: new_sample_one/cultures_vitals.parquet 
Start merge with: new_sample_one/antibiotic_class_exposure.parquet 


MemoryError: Unable to allocate 40.1 GiB for an array with shape (78, 69015096) and data type object